### ISSUE TITLE
我的加到项目中，效果和你的这个不一样

### ISSUE THREAD

**Issue by ThinkWYP** [kot32go/KShareViewActivityManager#6]
我的应用场景是这样的，在瀑布流中用的，然后点击的时候点击的view会白一下，然后第二个页面展开，并不是以分享的形式过去的
http://ww3.sinaimg.cn/mw690/005yqym4gw1f0bx3qd80xg30ax0dwhdu.gif

**Comment by kot32go** [comment]
你QQ多少？

**Comment by ThinkWYP** [comment]
@kot32go 571626345

**Comment by kot32go** [comment]
还不能够支持第二个页面的layout是动态展现的情况，抱歉
