### ISSUE TITLE
code review的2处问题

### ISSUE THREAD

**Issue by Piasy** [kot32go/KShareViewActivityManager#7]
1. [findAllTargetViews中，new的ShareViewInfo，构造函数内传入了一个new的Point对象](https://github.com/kot32go/KShareViewActivityManager/blob/b587119457c340b3c13a471124c092e9922294be/kshareviewactivitylibrary%2Fsrc%2Fmain%2Fjava%2Fcom%2Fkot32%2Fkshareviewactivitylibrary%2Fmanager%2FKShareViewActivityManager.java#L422)，但是这个对象会在`beforeAnimation`的循环里面重新赋值为一个new出来的Point对象，不合理吧？
2. [此处](https://github.com/kot32go/KShareViewActivityManager/blob/b587119457c340b3c13a471124c092e9922294be/kshareviewactivitylibrary%2Fsrc%2Fmain%2Fjava%2Fcom%2Fkot32%2Fkshareviewactivitylibrary%2Fmanager%2FKShareViewActivityManager.java#L233)显然可能导致NullPointerException，IDE是有提示的。

**Comment by kot32go** [comment]
竟然忘记return了。。现在代码有点乱，在功能完善后会好好重构一下， 非常感谢！O(∩_∩)O

**Comment by Piasy** [comment]
这个repo也可以了解一下哈：https://github.com/takahirom/PreLollipopTransition

**Comment by kot32go** [comment]
多谢指导！！能加个好友吗？我微信号 kotkot

**Comment by Piasy** [comment]
加qq吧，我的qq号：`200842165`
