### ISSUE TITLE
一些问题

### ISSUE THREAD

**Issue by lubeast** [kot32go/KShareViewActivityManager#8]
- 如果共享组件大小发生变化，放大和位移不是同时进行。
- 共享组件放大的时候，其中内容会变形。

我粗略使用了一下，发现了以上两个问题，不知是否可以解决 :D

**Comment by kot32go** [comment]
嗯，是的，如果同时进行，位移会发生飘逸，导致没法准确到第二个Activity 的位置，现在还没想到什么好解决的办法。
第二点你可以在onAnimationStart 的回调函数里面先将你不想形变的属性设置为空就好了 :D

**Comment by lubeast** [comment]
好的，谢谢你的回复 :)

**Comment by kot32go** [comment]
同步缩放和位移的问题已经解决了，可以同时进行了 :dancers:

**Comment by lubeast** [comment]
Gooood Job !!! 我还正看呢，做位移应该不会出现那种情况的，你已经解决了，哈哈 :dango: 

还有，我找到了一个`tianzhijiexian`一年前写的[ActivityOptionsICS](https://github.com/tianzhijiexian/ActivityOptionsICS) 挺不错的，不过现在他貌似已经停更了，你可以借鉴一下然后超过他！
